### ISSUE TITLE
 Implement struct: histogram

### ISSUE THREAD

**Issue by FreddyWordingham** [aetherus-wg/Aetherus#7]
Histogram data structure.

**Comment by sammorrell** [comment]
I migrated the `data::Histogram` type during the migration of the `data` module in 7d65745ec2ad879a57a778cf052f6917328bb627. All that we require now is to document and provide unit tests for it. This is also a part of issues #16 and #17.

**Comment by sammorrell** [comment]
Merged into `main` as part of PR 21 (https://github.com/aetherus-wg/Aetherus/pull/21) on 2022-01-10. Closing issue.
